[package]
name = "hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cavp_tester = { path = "../../CAVP-Tester" }
tokio = {version="1.41.1", features=["full"]}
